### ISSUE TITLE
Integrate with Bitbucket's "Pull Request POST" hook

### ISSUE THREAD

**Issue by bmannix** [nishio-dens/bitbucket-pullrequest-builder-plugin#12] opened 2014-06-16 14:52 UTC
Bitbucket provides a hook that fires when a pull request is created or when configurable events occur.  It would be very nice if this plugin could integrate with bitbucket's hook (even if it was just a tickle that would kick off the existing polling) so the cron schedule would become unnecessary, builds would fire immediately, and it would cut down on network traffic.

https://confluence.atlassian.com/display/BITBUCKET/Pull+Request+POST+hook+management

**Comment by akhyrul** [comment] 2015-03-24 11:09
+1

**Comment by Epilgrim** [comment] 2015-05-08 09:18
+1

**Comment by DoDoENT** [comment] 2015-10-19 15:40
+1

**Comment by tgeens** [comment] 2015-10-23 17:11
That link 404's now ?

Could this be a duplicate of #60 ?

**Comment by bmannix** [comment] 2015-10-23 18:00
#60 - is a generic request for push notification based builds (one of which could be the pull request builder).  But yeah, I'd say that #60 is essentially a duplicate of this (much older) ticket.  

The new link is: https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html

**Comment by itsSaad** [comment] 2017-07-11 23:11
2 years later. We still need this. 👍

**Comment by lifeofguenter** [comment] 2017-11-23 21:28
+1

**Comment by ip1981** [comment] 2017-11-24 22:34
+1 :)

**Closed** 2018-10-08 20:03 UTC
Labels: aged out
