### ISSUE TITLE
"Rebuild if destination branch changes?" doesn't work

### ISSUE THREAD

**Issue by gd-yunasc** [nishio-dens/bitbucket-pullrequest-builder-plugin#128] opened 2017-09-01 11:50 UTC
I have Jenkins job, setup manually with this checkbox selected.

I have 2 open PRs.
Both have been checked.

I merge the first one.
Expected: second PR is rechecked.
Actual: nothing happens with second PR.

<img width="471" alt="screen shot 2017-09-01 at 13 47 47" src="https://user-images.githubusercontent.com/23258511/29968550-71c4e9c8-8f1c-11e7-9351-352e23a815d2.png">
I've checked code, looks like method responsible for this isn't used.

Could it be because of we're using forks, and thus I'm performing local merge manually (i.e. by shell steps) without pushing from local to origin?

**Comment by CodeMonk** [comment] 2018-10-08 20:27
Duplicate of #132

**Closed by CodeMonk** 2018-10-08 20:27 UTC
