### ISSUE TITLE
NullPointerException while build start

### ISSUE THREAD

**Issue by sigalx** [nishio-dens/bitbucket-pullrequest-builder-plugin#57] opened 2015-08-20 23:49 UTC
Recently (2 days ago) I have discovered a problem that Bitbucket pull requests do not cause the build start. None of settings has been changed. Got some information from Jenkins log /var/log/jenkins/jenkins.log:

Aug 21, 2015 2:42:00 AM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder run
INFO: Build Start.
Aug 21, 2015 2:42:00 AM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository getTargetPullRequests
INFO: Fetch PullRequests.
Aug 21, 2015 2:42:03 AM hudson.triggers.Trigger checkTriggers
WARNING: bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run() failed for hudson.model.FreeStyleProject@caa4a34[Timebook]
java.lang.NullPointerException
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isBuildTarget(BitbucketRepository.java:128)
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:56)
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:30)
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:153)
        at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
        at hudson.triggers.Trigger$Cron.doRun(Trigger.java:217)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mvanbaak** [comment] 2015-09-10 14:31
I have the same problem :(

**Comment by mvanbaak** [comment] 2015-09-10 14:43
And I found out what the problem is. There is a PR to a deleted branch!
I fixed the PR and everything started working again :)

**Comment by sigalx** [comment] 2015-09-11 11:10
Same for me, it works. Thanks!

**Comment by mvanbaak** [comment] 2015-09-14 10:19
Still I think this should not break the job. There should be some checks around it to see if both source and destination still exists. 

But at least we know why it goes wrong and how to 'fix' it

**Comment by b091** [comment] 2015-11-12 09:58
+1

**Comment by NicoTexas** [comment] 2017-05-23 02:01
Indeed, it should be fixed.
We just spent few hours to try to find out what was happening. Target branch deleted created nullpointerexception.

**Closed** 2018-10-08 20:02 UTC
Labels: aged out
