### ISSUE TITLE
Many errors on Jenkins log

### ISSUE THREAD

**Issue by magnocosta** [nishio-dens/bitbucket-pullrequest-builder-plugin#103] opened 2017-01-24 22:48 UTC
There are many error messages in my Jenkins log,

I saw that there is a new commit that uses bitbucket api v2. When will this version be available in Jenkins updates?

Follow stacktrace:

> invalid pull request response.
> org.codehaus.jackson.JsonParseException: Unexpected character ('R' (code 82)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
>  at [Source: java.io.StringReader@3ec42c1f; line: 1, column: 2]
> 	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
> 	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
> 	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
> 	at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1198)
> 	at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:485)
> 	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
> 	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
> 	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863)
> 	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.parse(ApiClient.java:254)
> 	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getPullRequests(ApiClient.java:86)
> 	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:91)
> 	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
> 	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:187)
> 	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
> 	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
> 	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 

Thanks =)

**Comment by fulax** [comment] 2017-02-01 14:21
Same here, we tried to enable logging to see the actual response, without any success.

The code does `parse(get(..))` so if the response's Content-Type is not Json or the status code is not 200, it tries to parse the response, and fails to display the HTTP Response body which could help us investigate the issue.

**Comment by ghusse** [comment] 2017-02-02 10:56
We modified the code to log responses in case of errors, recompiled it and here is the complete response received from Bitbucket:

> Rate limit for this resource has been exceeded

**Comment by garrethmcdaid** [comment] 2017-02-02 15:50
The performance of this plugin has become very inconsistent over the last 72 hours. Execution of new builds, particularly using TTP functionality, is inconsistent. Can only presume this is something to go with Bitbucket tightening the rate limiting on their API. Plugin is effectively useless at the moment.

**Comment by ghusse** [comment] 2017-02-02 16:10
Same here.

It appears that some responses from Bitbucket are completely empty, causing an error in the plugin.

**Comment by garrethmcdaid** [comment] 2017-02-02 16:28
Published rate limits for Bitbucket API are reasonably generous.

https://confluence.atlassian.com/bitbucket/rate-limits-668173227.html

Apparently they are per hour, but I am see Rate Limit responses all the time eg at 1 minute past the hour.

**Comment by ghusse** [comment] 2017-02-03 09:39
We reduced the cron frequency on our server, and created a second user for requesting Bitbucket.

We still have Rate Limit errors on some of our repositories. But independently it seems that PRs are randomly build by Jenkins. We cannot rely on PR building anymore, it seems partially broken.

**Comment by garrethmcdaid** [comment] 2017-02-03 09:52
I have an open ticket with Bitbucket. I will update on their responses. They have asked for log evidence, which I have provided.

**Comment by garrethmcdaid** [comment] 2017-02-06 19:59
This is the response I got from Bitbucket:

So we did change the throttling on the API to help performance. After some research it appears that you were making 3k+ calls/hour before we throttled-- the specific API you're hitting is very expensive for us, which is why this needs to be done. A quick question: is there a reason to be polling this aggressively or is there a large number of open pull requests here?
We do have a PR created for this plugin to possibly use a less expensive API endpoint: https://github.com/jenkinsci/bitbucket-pullrequest-builder-plugin/pull/7
This one is currently not rate limited (but we cannot guarantee this in the future)

**Comment by ghusse** [comment] 2017-02-07 08:08
Thanks for the update, I'll build master and try this version

**Comment by ghusse** [comment] 2017-02-07 11:43
When using master, I get NullPointerExceptions. If I fix this error, the plugin seems to be working fine, but builds are not launched...

It seems that the PR broke something.

**Comment by jkobus** [comment] 2017-02-09 11:16
Im also experiencing this problem but only for one repository in my team.

**Comment by garrethmcdaid** [comment] 2017-02-09 11:33
I've throttled all our jobs back from "* * * * *" to "*/5 * * * *" and that seems to have stabilised the situation.

**Comment by jkobus** [comment] 2017-02-09 12:35
@garrethmcdaid I did the same about an hour ago and I can confirm that it worked.

**Comment by jkobus** [comment] 2017-02-10 09:48
After updating the shedule jenkins started to continiously rebuild all pr's (refs #62)

`
POST state INPROGRESS to https://bitbucket.org/api/2.0/repositories/null/null/commit/5fa518995d69/statuses/build with key jenkins-85ed65ec66bdc0537a94b1dfd4eb7b54 with response {"type": "error", "error": {"message": "Repository null/null not found"}}
`

**Comment by ghusse** [comment] 2017-02-10 09:50
I think I have a fix on this issue. The response does not seem to return the repository name and owner in the response.

The fix consists in using values from the plugin config instead of the response. I'm testing it on our installation to see if it resolves the issue.

**Comment by jkobus** [comment] 2017-02-10 10:07
Thank you. I will test it in a few minutes.

**Comment by despairblue** [comment] 2017-02-10 10:17
@ghusse Awesome. I was just about to open an issue for this, jenkins is going crazy since 12 hours ago. Did Bitbucket change their responses or how could this happen without changing jenkins or the plugin?

**Comment by ghusse** [comment] 2017-02-10 10:19
I updated my PR to change the repository owner and name in another place. It seems to fix the issue on our server.

The downside is that I don't think it'll work when Pull Request are on another person's repository but it's not our case.

The Bitbucket response definitively changed, but I don't know this plugin enough to know what changed and all the impacts.

**Comment by garrethmcdaid** [comment] 2017-02-10 10:23
Hi @ghusse could I ask you for guidance on how to build your PR locally?

**Comment by ghusse** [comment] 2017-02-10 10:23
`mvn compile hpi:hpi`

**Comment by ghusse** [comment] 2017-02-10 10:24
(you can comment on the PR)

**Comment by Mercynary** [comment] 2017-02-10 11:35
Since yesterday the plugin goes completely mad and I got builds every 2m. Interestingly the link to the repository also seems to be wrong: https://bitbucket.org/null/null/pull-request/156

**Comment by christcake** [comment] 2017-02-10 11:42
Also seeing this issue, all our builds which use the plugin have been rebuilding all night.

We saw the same issue as others a couple of weeks ago with hitting the rate limit and dropped our cron schedule frequency to work around it.

**Comment by garrethmcdaid** [comment] 2017-02-10 11:45
This is known issue with Bitbucket API.

Patch (and build instructions) available here:

https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/105

**Comment by ccamp46** [comment] 2017-02-10 15:07
Just started happening to me as well last night.  throws all current PRs (3) back into queue after an executor starts working on one.  have the same null/null API call issue.

**Comment by AlSayedGamal** [comment] 2018-01-25 16:55
Still happening with me. any fix ?

**Comment by ip1981** [comment] 2018-01-25 17:43
>Still happening with me. any fix ?

Kind of https://github.com/ip1981/bbprb :)

**Comment by CodeMonk** [comment] 2018-10-08 20:04
Duplicate of #105

**Closed by CodeMonk** 2018-10-08 20:04 UTC
