### ISSUE TITLE
pullrequest-builder-plugin doesn't start 

### ISSUE THREAD

**Issue by nnakash** [nishio-dens/bitbucket-pullrequest-builder-plugin#149] opened 2018-04-10 08:42 UTC
Hello,
Can someone please help me understand why i don't see any attempt to check for pull request after i set everything up:
I used configured it by pipeline syntax and from the build trigger tab but nothing happen :( 

pipeline {
    agent any
        triggers{
            bitbucketpr(projectPath:'##@bitbucket.org:####/#####.git',
            cron:'* * * * *',
            credentialsId:'',
            username:'##@####.com',
            password:'######',
            repositoryOwner:'#####',
            repositoryName:'#####',
            branchesFilter:'',
            branchesFilterBySCMIncludes:false,
            ciKey:'',
            ciName:'',
            ciSkipPhrases:'',
            checkDestinationCommit:false,
            approveIfSuccess:false,
            cancelOutdatedJobs:true,
            commentTrigger:'test this please')
        }

**Comment by CodeMonk** [comment] 2018-09-26 23:52
@nnakash Can you provide logs, please?

Though, I suspect this is the same issue as #155 , which is fixed in master, but, has not yet been released.

**Comment by nnakash** [comment] 2018-09-27 06:05
Thanks for the response! 
 I will provide logs next week
Is there a version that i should check to see if it resolved? (when the current master going to be release?)

**Comment by CodeMonk** [comment] 2018-10-08 19:53
Closing this as a duplicate of #166

**Closed by CodeMonk** 2018-10-08 19:53 UTC
Labels: Throttling
