### ISSUE TITLE
Approve if build success not working

### ISSUE THREAD

**Issue by gitawego** [nishio-dens/bitbucket-pullrequest-builder-plugin#95] opened 2016-07-26 08:47 UTC
in jenkins 2.7.1, Approve if build success option doesn't work. any idea about this ?

**Comment by fcanela** [comment] 2017-10-23 13:13
Hello. I do not know if you still have the issue. Can you check the Jenkins logs to see if this lines appears?:

```
com.squareup.okhttp.internal.Platform$JdkWithJettyBootPlatform getSelectedProtocol
INFO: NPN/ALPN callback dropped: SPDY and HTTP/2 are disabled. Is npn-boot or alpn-boot on the boot class path?
```
I am having the same problem that you (described in #136) and I would love to check if they have the same cause so @nishio-dens can handle both at the same time.

**Comment by CodeMonk** [comment] 2018-09-27 00:51
@fcanela @gitawego Is this still an issue? It seems to be working for my installation.

Also, I'm marking this as a duplicate of #136

**Closed** 2018-09-27 00:51 UTC
Labels: duplicate
