### ISSUE TITLE
Scheduler and Pull Request builder not working correctly

### ISSUE THREAD

**Issue by dimitrez** [nishio-dens/bitbucket-pullrequest-builder-plugin#179] opened 2018-12-11 17:56 UTC
hey guys, i have this issue in last 3 month. I have Jenkins with Bitbucket Pull Request builder, all was working normally, but in last 3 month i not understanding why - sometimes after we have PR update or new PR plugin not starting build PR, help only restarting Jenkins. I investigate logs but in logs no error,  it feel likes that cron into plugin or Jenkins not working or have broken cache. I not have any idea how i can fix it or what yet investigate.

All other Jenkins tasks working correctlt (other tasks based on BitBucket hooks, Docker hooks, monitoring BitBucket repo chnges for branch.)

This is my currentt plugin config. 

![screen_2018-12-11_12-02-59](https://user-images.githubusercontent.com/19185339/49793126-1c093d00-fd3d-11e8-9b63-be453f043309.png)

I have Jenkins log for `bitbucketpullrequestbuilder.bitbucketpullrequestbuilder` log level `ALL` but in logs no any errors messages. If  need i can add log from Jenkins.

after restarting Jenkins sometimes all working correctly, but then after this problem is repeated.

_Originally posted by @dimitrez in https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/issues/72#issuecomment-446147538_

**Comment by CodeMonk** [comment] 2018-12-21 17:42
Duplicate of #180

**Closed by CodeMonk** 2018-12-21 17:42 UTC
