### ISSUE TITLE
The PR builder Job is not getting triggered

### ISSUE THREAD

**Issue by honey-george** [nishio-dens/bitbucket-pullrequest-builder-plugin#151] opened 2018-05-27 16:37 UTC
Jenkins version: 2.107.2
Bitbucket PR builder plugin version: 1.4.26

My Job is not getting triggered when a new PR is created (or) when the comment "test this please" is updated in the open PR. Please see my free-style job configuration below:

![image](https://user-images.githubusercontent.com/4378895/40588311-31922f22-61f9-11e8-8062-c5d8e7c83749.png)

I see the below NullPointerException in the jenkins logs @ /var/log/jenkins/jenkins.log

May 27, 2018 4:34:59 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started PersistentMaster-Worker
May 27, 2018 4:34:59 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished PersistentMaster-Worker. 0 ms
May 27, 2018 4:35:01 PM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient getAllValues
WARNING: invalid response.
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getAllValues(ApiClient.java:207)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getPullRequests(ApiClient.java:105)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:94)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:292)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

NOTE: I see a similar issue 28, but is not the case with me. Both my repo name in bitbucket and in PR builder config is in lowercase.

Please help, let me know what I am missing.

**Comment by CodeMonk** [comment] 2018-09-26 23:47
That looks like what happens when bitbucket rate limits. If I'm right, a couple of lines up, you'll see something like this: 
`Sep 25, 2018 3:12:01 AM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient send
WARNING: Response status: HTTP/1.1 429 Unknown Status Code URI: https://bitbucket.org/api/2.0/repositories/itautosys/app_web/pullrequests/?pagelen=50
Sep 25, 2018 3:12:01 AM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient getAllValues
WARNING: invalid response.
java.lang.NullPointerException`

**Comment by CodeMonk** [comment] 2018-10-08 19:52
Duplicate of #166

**Closed by CodeMonk** 2018-10-08 19:52 UTC
Labels: Throttling
