### ISSUE TITLE
Does this plugin work with BitBucket Server?

### ISSUE THREAD

**Issue by davetherave112** [nishio-dens/bitbucket-pullrequest-builder-plugin#140] opened 2017-12-11 23:23 UTC
...formerly known as Stash, the self-hosted bitbucket server.

**Comment by arthurbarros** [comment] 2018-01-31 19:01
wonder the same

**Comment by JavierLight** [comment] 2018-02-09 09:11
+1

**Comment by bblain7** [comment] 2018-02-15 20:49
+1
Looks like the bitbucket.org url is hardcoded. It would be nice if the destination url was an input instead.

**Comment by CaoimhinKing** [comment] 2018-02-20 10:21
+1, any further information on this would be nice

**Comment by gCardinal** [comment] 2018-03-01 19:33
+1

This plugin looks like it could pretty much do everything I need.

**Comment by CodeMonk** [comment] 2018-09-27 00:12
That's a great idea - marking this as an enhancement.

**Comment by CodeMonk** [comment] 2018-10-08 20:26
Duplicate of #167

**Closed by CodeMonk** 2018-10-08 20:26 UTC
Labels: enhancement, question
