### ISSUE TITLE
Plugin always fails to merge even when there are no merge conflicts

### ISSUE THREAD

**Issue by CVirus** [nishio-dens/bitbucket-pullrequest-builder-plugin#24] opened 2014-11-10 05:04 UTC
```
<a href=https://bitbucket.org/OtakuDevs/fer2etak/pull-request/5>#5 test</a>
Building in workspace /var/lib/jenkins/workspace/Fer2etak-branches
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@bitbucket.org:OtakuDevs/fer2etak.git # timeout=10
Fetching upstream changes from git@bitbucket.org:OtakuDevs/fer2etak.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --progress git@bitbucket.org:OtakuDevs/fer2etak.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/FER-6^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/FER-6^{commit} # timeout=10
Merging Revision 81c4913a2f00e55a7a361489b67ac14f0c28ba78 (refs/remotes/origin/FER-6) onto origin/development using default strategy
 > git rev-parse origin/development^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f origin/development
 > git merge 81c4913a2f00e55a7a361489b67ac14f0c28ba78 # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 81c4913a2f00e55a7a361489b67ac14f0c28ba78
ERROR: Branch not suitable for integration as it does not merge cleanly
[WARNINGS] Skipping publisher since build result is FAILURE
Skipping Cobertura coverage report as build was not UNSTABLE or better ...
Recording test results
ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
hudson.AbortException: No test report files were found. Configuration error?
    at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:116)
    at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:92)
    at hudson.FilePath.act(FilePath.java:981)
    at hudson.FilePath.act(FilePath.java:959)
    at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:89)
    at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:120)
    at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:137)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
    at hudson.model.Run.execute(Run.java:1784)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
[SLOCCount] Skipping results publication since the build is not successful
Finished: FAILURE
```

**Comment by jmh** [comment] 2015-02-02 22:33
I've just run into a similar situation. The pull request initially did not merge cleanly, so I merged the conflicting files into my feature branch and pushed again. However, jenkins is still complaining about a merge conflict despite BB and my local testing saying otherwise. Looking at the console output all the commit hashes look to be correct.

My prior tests with PRs all worked fine, but I was only giving it branches with no conflicts.

Here is the pertinent part of the output:
```
Building in workspace /var/lib/jenkins/workspace/XXXX
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@bitbucket.org:xxxx/xxxx.git # timeout=10
Fetching upstream changes from git@bitbucket.org:xxxx/xxxx.git
 > git --version # timeout=10
using GIT_SSH to set credentials BB access key
 > git -c core.askpass=true fetch --tags --progress git@bitbucket.org:xxxx/xxxx.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/feature/xxxx^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/feature/xxxx^{commit} # timeout=10
Merging Revision 98134c3a0e997d9b8b1eae01155006610d8c449f (refs/remotes/origin/feature/xxxx) onto origin/develop using default strategy
 > git rev-parse origin/develop^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f origin/develop
 > git merge 98134c3a0e997d9b8b1eae01155006610d8c449f # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 98134c3a0e997d9b8b1eae01155006610d8c449f
ERROR: Branch not suitable for integration as it does not merge cleanly: Could not merge 
```

**Comment by benschenker** [comment] 2015-03-06 16:14
Ran into a similar issue with a gitlab merge request builder.  Looks like I had a post-build action to publish JUnit test results but the xml it was pointing to had the wrong path.  When the configuration was changed to point to the new path, the problem went away.

**Comment by trumpetx** [comment] 2015-08-13 19:04
Like @CVirus, I am now getting this error and can't explain why.  No JUnit .xml paths like @benschenker has.  In some interesting debugging information, I'm using Gitlab's web hook plugin, not bitbucket's, but I'm getting the exact same error.

**Comment by amelnikoff** [comment] 2015-09-10 15:35
> ERROR: Branch not suitable for integration as it does not merge cleanly

I had this error on Windows, when git was not configured with _user.email_ and _user.name_

**Comment by urmet** [comment] 2015-10-13 11:12
Do you have your git clients configured(name/email)? I had a similar problem and the problem was that git complained about missing configuration that prevented it from creating the merge commit.

**Comment by ollisal** [comment] 2016-05-25 14:52
Try running the git commands up to the git merge from the log (although the fetch command probably doesn't work because of missing credentials), and you should see what's causing this. For me, it was the case of a non-fast-forward merge, and git merge wanting user.name and user.email to be configured in that case, similarly to @amelnikoff.

TBH I don't think this is even a problem of the pullrequest builder, rather it's the jenkins git SCM module, which is doing the merge here. It should at least print the full error from the git merge command, so it's clear when it's a merge conflict and when it's something else.

**Comment by lifeofguenter** [comment] 2016-05-27 11:48
having the same problem - I added git config user.name/email via cli and Jenkins configuration - unfortunately did not help.

**Comment by lifeofguenter** [comment] 2016-05-27 11:52
Actually after adding "Wipeout Workspace and full clone" I am getting this error:

```
13:50:29  > git rev-parse origin/feature/xxx-embeddable-widgets^{commit} # timeout=10
13:50:29 FATAL: Command "git rev-parse origin/feature/xxx-embeddable-widgets^{commit}" returned status code 128:
13:50:29 stdout: origin/feature/xxx-embeddable-widgets^{commit}
13:50:29 
13:50:29 stderr: fatal: ambiguous argument 'origin/feature/xxx-embeddable-widgets^{commit}': unknown revision or path not in the working tree.
13:50:29 Use '--' to separate paths from revisions, like this:
13:50:29 'git <command> [<revision>...] -- [<file>...]'
13:50:29 
13:50:29 hudson.plugins.git.GitException: Command "git rev-parse origin/feature/xxx-embeddable-widgets^{commit}" returned status code 128:
13:50:29 stdout: origin/feature/xxx-embeddable-widgets^{commit}
13:50:29 
13:50:29 stderr: fatal: ambiguous argument 'origin/feature/xxx-embeddable-widgets^{commit}': unknown revision or path not in the working tree.
13:50:29 Use '--' to separate paths from revisions, like this:
```

**Comment by ollisal** [comment] 2016-05-27 11:53
@lifeofguenter did you actually run the commands to verify that the problem is missing user.name/user.email for you?

Note that you should also run them as the same user as Jenkins would be using for the build, otherwise you might get different results.

If it's missing user.name/email you obviously need to also run git config --global as the correct user to set them - or set them without --global in the repo, but then it would be lost if you reset and recreate the workspace etc.

**Comment by lifeofguenter** [comment] 2016-05-27 11:54
@ollisal yup, it is part of the ansible setup, e.g. I run those commands as `jenkins` user - how can I fully replicate the commands? It seems that some commands are not shown in the console output?

**Comment by ollisal** [comment] 2016-05-27 12:00
@lifeofguenter is your branch actually called "feature/xxx-embeddable-widgets" (I guess with something secret instead of xxx, unless you're working on a porn site) and is it really in the repo Jenkins is checking out from?

i.e. verify your git SCM configuration for the job. "Repository URL" should be set to the repo URL where you push your feature branches, and "Branch Specifier" to "*/${sourceBranch}" generally when using the bitbucket pullrequests builder.

It might be some problem with branch names containing a slash though, I haven't checked how the plugin works with them myself

**Comment by lifeofguenter** [comment] 2016-05-27 12:09
Ok I might be lost in translation here. So I did follow (as much as possible) the `README.md`

* Repository URL: `git@bitbucket.org:${repositoryOwner}/${repositoryName}.git` (which is resolving to the owner + name of the forker)
* Branch specifier: `*/${sourceBranch}`
* RepositoryOwner: hardcoded to the upstream project
* RepositoryName: hardcoded to the upstream project

I am seeing now, that I might be mixing up the settings (after comparing it with the "Parameters" page of the build) - surely the goal is always to merge the forked branch into the upstream repository and then to build?

**Comment by lifeofguenter** [comment] 2016-05-27 15:18
Ok so without changing any of my settings, after the fork was updated (amend + force push) now suddenly the job is working.

Strange..

**Closed** 2018-10-08 20:03 UTC
Labels: aged out
